apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: my-push-secret
spec:
  data:
    - match:
        remoteRef:
          remoteKey: my-push-secret
        secretKey: uuid
      metadata:
        secretPushFormat: string
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: aws-sm
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: UUID
      name: uuid 